hidden-os merged to hidden
Nitrokey/nitrokey-documentation pull request #126
Opened 2023-01-04 17:31 UTC by Deashow

- merged "/linux/hidden-os-specific-partitioning.rst" to "/linux/hidden.rst"
- same for /mac and /windows
- deleting "hidden-os-specific-partitioning.rst" in /linux, /mac, /windows after merge

- testet seperate on "linunx/hidden.html", "mac/hidden.html" and "windows/hidden.html" => works fine

2023-01-05 09:28 UTC, Deashow commented
Uploaded a temporary solution for the warning "unknown image" but it didn't solve our main problem for all images.

2023-01-05 11:17 UTC, Deashow commented
Fixing some critical path issues because the "include" was doubled for different files.

2023-01-05 12:55 UTC, Deashow commented
nitrokey-documentation/storage/linux/openvpn-easyrsa.rst:388: WARNING: Could not lex literal_block as "bash". Highlighting skipped.

The problem was it was "code-block bash" but without correct terminal/shell syntax. So i changed "bash" into "none" which solved the highlighting warning.

2023-01-06 10:18 UTC, mmerklinger requested changes
See the comment about the code block below. Besides that good work! Thank you!

2023-01-06 10:18 UTC, mmerklinger commented on storage/linux/openvpn-easyrsa.rst
>         2. Create a Public Key Infrastructure (PKI) for the OpenVPN client
I don't see a reason why this was in a code block. Please remove the code block and have the enumeration without indentation there.

2023-01-06 10:35 UTC, egurn commented on storage/linux/openvpn-easyrsa.rst
>         2. Create a Public Key Infrastructure (PKI) for the OpenVPN client
Well, it looks like someone used this code-block to give an overview of all the steps and make some sort of ToC without actually creating one. :smiley: 

Since we generate a ToC, I think, you can safely remove that code-block (lines 388 to 397) altogether.

2023-01-06 11:39 UTC, Deashow commented
Got it "code-block:: none" (line 388-397) is deleted and could be merged.

2023-01-09 13:25 UTC, merged