adding installation method for mac via pipenv
Nitrokey/nitrokey-documentation pull request #346
Opened 2024-12-04 15:54 UTC by nitrosimon

fixes #341

2024-12-04 17:27 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> +-----------------
Use correct length lines to avoid warnings

2024-12-04 17:29 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> +To start the app run enter the workdirectory ``cd nitrokeyapp`` and run  ``pipenv run nitrokeyapp``
"run enter"?

2024-12-11 15:21 UTC, nitrosimon commented
fixes issue341

2024-12-14 00:13 UTC, daringer requested changes

2024-12-14 00:13 UTC, daringer commented on source/components/software/nk-app2/installation_mac.rst
> +2. Create a work directory ``mkdir nitrokeyapp``
please put those (and all the others) into separate block-code entries, so copying them out is more convenient, like this:
````suggestion
2. Create a work directory 
```bash
mkdir nitrokeyapp
```
````

2024-12-14 00:13 UTC, daringer commented on source/components/software/nk-app2/installation_mac.rst
> +2. pipenv update
codeblock missing

2025-01-14 13:51 UTC, nitrosimon commented on source/components/software/nk-app2/installation_mac.rst
> +2. pipenv update
use this more explicit code block isntead:     .. code-block::

2025-01-14 14:05 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> +This is the simplest way for now to install the Nitrokey App 2 on Mac. Further methods are being worked on.
It's "macOS"

2025-01-14 14:06 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> +Mac Install
It's "macOS"

2025-01-14 14:07 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> +To run the application, go into the workdirectory
"work directory"

2025-01-14 14:07 UTC, jans23 commented on source/components/software/nk-app2/installation_mac.rst
> + cd nitrokeyapp and run
?

2025-01-14 14:17 UTC, nitrosimon commented on source/components/software/nk-app2/installation_mac.rst
> +Mac Install
yep, but this is wrong multiple times in the documentation , ill make a new issue for fixing this in the whole documentation overall

2025-02-10 13:55 UTC, closed without merging

2025-02-10 13:55 UTC, nitrosimon commented
reopening with changes directly in the main repo for preview