adding basic draft for SE50 specific documentation
Nitrokey/nitrokey-documentation pull request #358
Opened 2024-12-13 20:17 UTC by nitrosimon

fixes #302

2024-12-15 16:09 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +SE50 Secure Element
It's SE05. But mainly use the term Secure Element in the subsequent text instead of SE05.

2024-12-15 16:09 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +
This lacks an introduction, that the NK3 contains a SE and for which purpose it is used.

2024-12-15 16:09 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +The SE550 is enabled by default if no key is already saved on the device. This is automatically the case after reset of the opcard or the whole device. Activating the SE50 will delete all current key
Unclear which keys you talk about. FIDO keys? PIV keys?

OPCard is a developer terminology but not expected to be known by users.

2024-12-15 16:09 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +* NIST P-521 (secp256r1/prime256v1, secp384r1/prime384v1, secp521r1/prime521v1)
different key lengths are mixed.

2024-12-15 16:09 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +* SECP256K1 (Test release)
I think it should be lower case to be consistent with the above alogorithms.

2024-12-25 15:49 UTC, nitrosimon commented on source/components/nitrokeys/nitrokey3/SE50.rst
> +* NIST P-521 (secp256r1/prime256v1, secp384r1/prime384v1, secp521r1/prime521v1)
taken this from the shop page https://shop.nitrokey.com/shop/nk3cn-nitrokey-3c-nfc-148#attr= maybe we should fix it there too

2024-12-26 06:33 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/index.rst
> +    The Secure Element <secure-element>
Avoid "the"

2024-12-26 06:34 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/secure-element.rst
> +| Algorithm              | RSA 2048 | RSA-3072 | RSA-4096 | ECC 256-521 bit | AES-128/256 bit | SHA (SHA-256,SHA-384,SHA-512) | NIST P-256 secp256r1/prime256v1 | NIST P-384 (secp384r1/prime384v1) | N
Easier to read on smart phone screens if you swap columns and row. Also be consistent in naming of algorithms.

2025-01-06 10:22 UTC, sosthene-nitrokey requested changes

2025-01-06 16:34 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/secure-element.rst
> +Additional Features
Maybe you can find a headline which fits better.

2025-01-12 16:35 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/secure-element.rst
> +PIV uses the Secure Element. OpenPGP Card can be configured to use the Secure Element or not in which case a software-only implementation is used. Passwords and FIDO2 don't use the Secure Element, bu
> ... specific use cases, like additional randomness

Which other use cases?

2025-01-12 16:36 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/secure-element.rst
> +This is automatically the case after resetting the OpenPGP Card or the whole Nitrokey. Manually activating the Secure Element for the OpenPGP Card will delete all existing keys.
> Manually activating the Secure Element for the OpenPGP Card will delete all existing keys.

Better make this a warning block.

2025-01-12 16:36 UTC, jans23 commented on source/components/nitrokeys/nitrokey3/secure-element.rst
> +| ECC 256-521 bit                         | ✓                   | ✓                      |
What is ECC exactly? I assume this is covered by the ciphers below already.

2025-02-24 18:26 UTC, nitrosimon commented
superseeded by new pr from within the repo for preview

2025-02-24 18:26 UTC, closed without merging